version: "3.7"
services:
    nginx:
        build: ./docker/nginx
        ports:
            - "8081:80"
        links:
            - phpfpm
        volumes:
            - ./docker/nginx/application.conf:/etc/nginx/conf.d/application.conf
            - .:/application
    phpfpm:
        build: ./docker/php-fpm
        ports:
            - "9000:9000"
        volumes:
            - .:/application
        tty: true
    mysql:
        image: 'mysql'
        ports:
            - '3311:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=d9s37Kg3PFHhs975
            - MYSQL_USER=api-user
            - MYSQL_PASSWORD=DaY7t9MH4PLJTCZC
            - MYSQL_DATABASE=api