#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\Controller\HomeController::register
    methods: POST

authentication_token:
    path: /authentication_token
    methods: ['POST']